name: build
on:
  push:
jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: make firsttime
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: latest # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            main.exe
          name: dev
          tag_name: dev
